DSD: 1500.0
DSO: 1000.0
accuracy: 0.5
convert: false
dDetector:
- 2.
- 2.
dVoxel:
- 1.
- 1.
- 1.
filter: null
mode: cone
nDetector:
- 256
- 256
nVoxel:
- 256
- 256
- 256
lrVol:
- 256
- 256
- 256
noise: 0
normalize: true
numTrain: 50
numVal: 100
offDetector:
- 0
- 0
offOrigin:
- 0
- 0
- 0
randomAngle: false
rescale_intercept: 0.0
rescale_slope: 1.0
startAngle: 0.0
totalAngle: 180.0
