exp:
  expdir: ./logs/
  datadir: ./data/proj_num_tests/MELA0085_num70.pickle
network:
  net_type: mlp # WIRE
  num_layers: 6
  hidden_dim: 256 # 32
  skips: [2]
  out_dim: 1
  last_activation: sigmoid
  bound: 0.3
encoder:
  encoding: hashgrid
  input_dim: 3
  num_levels: 16
  level_dim: 2
  # base_resolution: 16
  base_resolution: 32
  log2_hashmap_size: 19
render:
  n_samples: 768
  n_fine: 0
  perturb: True
  raw_noise_std: 0.
  netchunk: 409600
train:
  epoch: 1500
  n_batch: 1
  n_rays: 2048
  lrate: 0.00001
  lrate_gamma: 0.1
  lrate_step: 1500
  resume: False
log:
  i_eval: 250  # Epoch for evaluation
  i_save: 500  # Epoch for saving