exp:
  expdir: ./logs/Pretrain
  conf: up512.yml
  upsample: trilinear
network:
  net_type: mlp # WIRE
  num_layers: 6
  hidden_dim: 256 # 32
  skips: [2]
  out_dim: 1
  last_activation: relu
  bound: 0.3
encoder:
  encoding: hashgrid
  input_dim: 3
  num_levels: 16
  level_dim: 4
  base_resolution: 8  # 16 takes too many memory
  log2_hashmap_size: 24
render:
  n_samples: 960
  n_fine: 0
  perturb: True
  raw_noise_std: 0.
  netchunk: 409600
train:
  epoch: 20
  n_batch: 4
  lrate: 0.0001
  lrate_gamma: 0.1
  lrate_step: 10
  resume: True
log:
  i_eval: 5  # Epoch for evaluation
  i_save: 10  # Epoch for saving
